// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateTask implements createTask operation.
	//
	// Create request task.
	//
	// POST /tasks
	CreateTask(ctx context.Context, req *CreateTaskInput) (*CreateTaskOutput, error)
	// GetHealthStatus implements getHealthStatus operation.
	//
	// Check service is health.
	//
	// GET /health
	GetHealthStatus(ctx context.Context) error
	// GetTaskStatus implements getTaskStatus operation.
	//
	// Get task status.
	//
	// GET /tasks/{taskID}
	GetTaskStatus(ctx context.Context, params GetTaskStatusParams) (GetTaskStatusRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
