// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTask implements createTask operation.
//
// Create request task.
//
// POST /tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *CreateTaskInput) (r *CreateTaskOutput, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthStatus implements getHealthStatus operation.
//
// Check service is health.
//
// GET /health
func (UnimplementedHandler) GetHealthStatus(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GetTaskStatus implements getTaskStatus operation.
//
// Get task status.
//
// GET /tasks/{taskID}
func (UnimplementedHandler) GetTaskStatus(ctx context.Context, params GetTaskStatusParams) (r GetTaskStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}
