// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetTaskStatusParams is parameters of getTaskStatus operation.
type GetTaskStatusParams struct {
	// ID of task to return.
	TaskID uuid.UUID
}

func unpackGetTaskStatusParams(packed middleware.Parameters) (params GetTaskStatusParams) {
	{
		key := middleware.ParameterKey{
			Name: "taskID",
			In:   "path",
		}
		params.TaskID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetTaskStatusParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTaskStatusParams, _ error) {
	// Decode path: taskID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "taskID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TaskID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "taskID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
